version: "3"
services:

 gocalc:
   build: ./gocalc
   command: ['./app']
   ports:
      - "7000:7000"
   links:
   - db
   volumes:
   - ./gocalc:/app
   environment:
      - POSTGRES_URI=postgres://postgres:postgres@db/postgres?sslmode=disable
      - LISTEN_ADDRESS=:7000
   depends_on: 
       db:
           condition: service_healthy
   
   
 db:
  image: postgres:latest
  environment: 
       PGUSER: postgres
       POSTGRES_PASSWORD: postgres
  ports:
      - "7001:5432"
  healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
 proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - gocalc
 
      
 
   
 

